### ISSUE TITLE
Install will not work with "LICENSE" file, but succeeds with "License" file.

### ISSUE THREAD

**Issue by ghost** [donya/Kulitta#2]
Hi Dr. Quick,

I don't know if this was just my machine or not, but after installing all the dependencies and trying to `cabal install` I got this prompt:

```
05:20:21 => sudo cabal install
Resolving dependencies...
Configuring Kulitta-2.2.0...
Warning: The 'license-file' field refers to the file 'License' which does not
exist.
Building Kulitta-2.2.0...
Preprocessing library Kulitta-2.2.0...
In-place registering Kulitta-2.2.0...
setup: License: does not exist
Failed to install Kulitta-2.2.0
cabal: Error: some packages failed to install:
Kulitta-2.2.0 failed during the final install step. The exception was:
ExitFailure 1
05:20:31 => 
```

`touch`ing a `License` file fixed the issue.

**Comment by donya** [comment]
Hi Andrew, I'm curious what OS was this on? I see it's showing up as "LICENSE" when viewing github through a browser, but on all install tests I've done it somehow becomes "License" when downloaded, which is weird. I'll try to fix this inconsistency.

-Donya

-----Original Message-----

**Comment by ghost** [comment]
I'm currently on Ubuntu 14.04; it might be a Linux thing, yeah.

On Tue, Mar 29, 2016 at 9:18 AM Donya Quick notifications@github.com
wrote:

> Hi Andrew, I'm curious what OS was this on? I see it's showing up as
> "LICENSE" when viewing github through a browser, but on all install tests
> I've done it somehow becomes "License" when downloaded, which is weird.
> I'll try to fix this inconsistency.
> 
> -Donya
> 
> -----Original Message-----
> From: Andrew Quinn notifications@github.com
> To: donya/Kulitta Kulitta@noreply.github.com
> Sent: Tue, Mar 29, 2016 5:23 am
> Subject: [donya/Kulitta] Install will not work with "LICENSE" file, but
> succeeds with "License" file. (#2)
> 
> Hi Dr. Quick,
> I don't know if this was just my machine or not, but after installing all
> the dependencies and trying to cabal install I got this prompt:
> 05:20:21 => sudo cabal install
> Resolving dependencies...
> Configuring Kulitta-2.2.0...
> Warning: The 'license-file' field refers to the file 'License' which does
> not
> exist.
> Building Kulitta-2.2.0...
> Preprocessing library Kulitta-2.2.0...
> In-place registering Kulitta-2.2.0...
> setup: License: does not exist
> Failed to install Kulitta-2.2.0
> cabal: Error: some packages failed to install:
> Kulitta-2.2.0 failed during the final install step. The exception was:
> ExitFailure 1
> 05:20:31 =>
> 
> touching a License file fixed the issue.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/donya/Kulitta/issues/2#issuecomment-202889608
> 
> ## 

   -
   https://www.linkedin.com/in/aquinn2

**Comment by donya** [comment]
Thanks - I was able to reproduce the problem just now and pushed a fix.

-----Original Message-----
